using System;
using ProjectEuler.Core;

namespace ProjectEuler
{
    [Problem(45)]
    internal sealed class Problem45 : BaseProblem
    {
        public override DateTime DateSet{get {return new DateTime(2003, 6, 6);}}

        public override string Title
        {
            get
            {
                return "After 40755, what is the next triangle number that is also pentagonal and hexagonal?";
            }
        }

        public override string Description
        {
            get
            {
                return @"Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.";
            }
        }

        public override long? ExpectedAnswer{get {return null;}}
    }
}
