using System;
using ProjectEuler.Core;

namespace ProjectEuler
{
    [Problem(44)]
    internal sealed class Problem44 : BaseProblem
    {
        public override DateTime DateSet{get {return new DateTime(2003, 5, 23);}}

        public override string Title
        {
            get
            {
                return "Find the smallest pair of pentagonal numbers whose sum and difference is pentagonal.";
            }
        }

        public override string Description
        {
            get
            {
                return @"Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk  Pj| is minimised; what is the value of D?";
            }
        }

        public override long? ExpectedAnswer{get {return null;}}
    }
}
