using System;
using ProjectEuler.Core;

namespace ProjectEuler
{
    [Problem(2)]
    internal sealed class Problem02 : BaseProblem
    {
        public override DateTime DateSet{get {return new DateTime(2001, 10, 19);}}

        public override string Title
        {
            get
            {
                return "Find the sum of all the even-valued terms in the Fibonacci sequence which do not exceed one million.";
            }
        }

        public override string Description
        {
            get
            {
                return @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed one million.";
            }
        }

        public override long? ExpectedAnswer{get {return 1089154;}}
    }
}
